---
version: '3'

services:
  aws-tools:
    image: entechlog/aws-tools${AWS_TOOLS_VERSION_TAG}
    container_name: aws-tools
    build: ./docker/
    command: 
      - bash 
      - -c 
      - |
        echo "Launching aws-tools"
        sleep infinity
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - type: bind
        source: /C
        target: /C
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - TZ=Etc/GMT
      - SAM_CLI_TELEMETRY=false
      